# Generated by Django 4.0 on 2022-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alunos_arte1_alunos_arte2_alunos_arte3_alunos_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='aluno',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
