# Generated by Django 4.0 on 2022-01-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alunos_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='aluno',
            field=models.BooleanField(default=False),
        ),
    ]
