# Generated by Django 4.0 on 2022-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_alunos_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='colaborador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='aluno',
            field=models.BooleanField(default=True),
        ),
    ]
